version: '3.9'

services:

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus/
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090
    environment:
      TZ: "Asia/Yekaterinburg"
    networks:
      - default
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    container_name: grafana
    hostname: grafana
    environment:
      TZ: "Asia/Yekaterinburg"
      environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/var/lib/grafana/dashboards/node-exporter-full_rev27.json"
    networks:
      - default
    restart: unless-stopped  