Vagrant.configure("2") do |config|
  #Box for VM
  config.vm.box = "generic/ubuntu2004"
  #VM hypervisor
  config.vm.provider "virtualbox" do |vb|
  #Name VM
  vb.name = "VagrantVM-test"
  #Gui interface
  vb.gui = false
  #CPU core
  vb.cpus = 1
  vb.memory = "2048"
  #Hostname for VM
  config.vm.hostname = "vagrantvm"
  #Username
  config.ssh.username = 'vagrant'
  #Password
  config.ssh.password = 'vagrant'
  #Login to username & password
  config.ssh.keys_only = false
  #Disable gen ssh key
  config.ssh.insert_key = false
  #Network
  #config.vm.network "public_network", ip: "10.0.2.15"
  #Sync folder
  config.vm.synced_folder "./ansible-temp", "/home/vagrant/ansible-temp",
  owner: "vagrant", group: "vagrant"
  config.vm.synced_folder "./docker-temp", "/home/vagrant/docker-temp",
  owner: "vagrant", group: "vagrant"
  #Port forwarding
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 9100, host: 9100
  config.vm.network "forwarded_port", guest: 9000, host: 9000
  config.vm.network "forwarded_port", guest: 9090, host: 9090
  #Start shell script
  config.vm.provision "provision", type: "shell", path: "provision.sh"
 end
 end

