---
- hosts: local
  become: yes
  become_method: sudo
  
  tasks:
  - name: Package installation
    apt:
      name:
        - curl
        - wget
        - apt-transport-https
        - ca-certificates
        - software-properties-common
      state: latest
    tags:
      - package